### ISSUE TITLE
[Bug]: MineTogether mod button is being shifted in escape menu

### ISSUE THREAD

**Issue by Raidobw2** [Fuzss/bettermodsbutton#7]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

BetterModsButton-v3.2.3-1.18.2-Forge.jar

### Notes (Required)

Button in top right is moved outside the screen:

![image](https://user-images.githubusercontent.com/17010632/200500473-9b56d001-76c8-4833-9e8f-55fbc72264ea.png)

I've reported this at https://github.com/CreeperHost/MineTogether/issues/658 originally, it looks like https://github.com/Fuzss/bettermodsbutton/blob/ef550af2b67a7d3c0d6846f6ce72046b9fec29c3/src/main/java/fuzs/bettermodsbutton/client/handler/ModScreenHandler.java#L164-L174 might be causing the issue by shifting all buttons up a few pixels?

Thanks in advance for checking it out!

P.S. Issue seems to be on 1.19+ too

### latest.log (Optional)

N/A

**Comment by Fuzss** [comment]
Fixed in latest versions.
