### ISSUE TITLE
[Suggestion]: Add an improved search system since the forge one is non-sensicle

### ISSUE THREAD

**Issue by RandomGuy91** [Fuzss/bettermodsbutton#8]
### Suggestion (Required)

For some reason, the Forge mod search screen is super ugly and not ordered very well. Could you improve it if you have time? I would use Configured by Mr. Crayfish but it conflicts with a few mods. Thanks!

**Comment by Fuzss** [comment]
You mean Catalogue? What mods does it conflict with?

**Comment by RandomGuy91** [comment]
Sry, yh. Mods with custom entity models or something. It's on the catalogue issues page if you want to take a look: https://github.com/MrCrayfish/Catalogue/issues/44

**Comment by RandomGuy91** [comment]
Tho, it appears it's been fixed. Still, could be a good idea ;)

**Comment by Fuzss** [comment]
Well I'm not gonna make a new mod just because the predominant mod has / had a small issue. Thanks for the suggestion though.

**Comment by RandomGuy91** [comment]
Yh, I can understand that
